apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-2
  labels:
    dashboards: "grafana-2"
    exists: ""
spec:
  client:
    preferIngress: true
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: root
      admin_password: secret
  ingress:
    spec:
      ingressClassName: nginx
      rules:
        - host: grafana2.127.0.0.1.nip.io
          http:
            paths:
              - backend:
                  service:
                    name: grafana-2-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
