resources:
  - crds.yaml
  - Namespace.yaml
  - ServiceAccount.yaml
  - Service.yaml
  - Deployment.yaml
  - ClusterRoleBinding.yaml
  - ClusterRole.yaml
patches:
  - target:
      kind: ClusterRole
    patch: |
      - op: replace
        path: /metadata/name
        value: grafana-operator-permissions
